// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesHeroes.Data;

#nullable disable

namespace HQ_Webb.Migrations
{
    [DbContext(typeof(RazorPagesHeroesContext))]
    [Migration("20240408152955_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("HQ_Lib.Heroes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentBody")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<double>("Gold")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxBody")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Heroes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Heroes");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HQ_Lib.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentBodyModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMindModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefenceModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeroesId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSpell")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Isequibt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxBodyModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMindModifier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("WeaponDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroesId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("HQ_Lib.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodyModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefenceModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeroesId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Isequibt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("WeaponDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroesId");

                    b.ToTable("Weapon");
                });

            modelBuilder.Entity("HQ_Lib.Barbarian", b =>
                {
                    b.HasBaseType("HQ_Lib.Heroes");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SpellCaster")
                        .HasColumnType("INTEGER");

                    b.ToTable("Heroes", t =>
                        {
                            t.Property("PlayerName")
                                .HasColumnName("Barbarian_PlayerName");

                            t.Property("SpellCaster")
                                .HasColumnName("Barbarian_SpellCaster");
                        });

                    b.HasDiscriminator().HasValue("Barbarian");
                });

            modelBuilder.Entity("HQ_Lib.Dwarf", b =>
                {
                    b.HasBaseType("HQ_Lib.Heroes");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SpellCaster")
                        .HasColumnType("INTEGER");

                    b.ToTable("Heroes", t =>
                        {
                            t.Property("PlayerName")
                                .HasColumnName("Dwarf_PlayerName");

                            t.Property("SpellCaster")
                                .HasColumnName("Dwarf_SpellCaster");
                        });

                    b.HasDiscriminator().HasValue("Dwarf");
                });

            modelBuilder.Entity("HQ_Lib.Elf", b =>
                {
                    b.HasBaseType("HQ_Lib.Heroes");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SpellCaster")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Elf");
                });

            modelBuilder.Entity("HQ_Lib.Rough", b =>
                {
                    b.HasBaseType("HQ_Lib.Heroes");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SpellCaster")
                        .HasColumnType("INTEGER");

                    b.ToTable("Heroes", t =>
                        {
                            t.Property("PlayerName")
                                .HasColumnName("Rough_PlayerName");

                            t.Property("SpellCaster")
                                .HasColumnName("Rough_SpellCaster");
                        });

                    b.HasDiscriminator().HasValue("Rough");
                });

            modelBuilder.Entity("HQ_Lib.Item", b =>
                {
                    b.HasOne("HQ_Lib.Heroes", null)
                        .WithMany("items")
                        .HasForeignKey("HeroesId");
                });

            modelBuilder.Entity("HQ_Lib.Weapon", b =>
                {
                    b.HasOne("HQ_Lib.Heroes", null)
                        .WithMany("weapons")
                        .HasForeignKey("HeroesId");
                });

            modelBuilder.Entity("HQ_Lib.Heroes", b =>
                {
                    b.Navigation("items");

                    b.Navigation("weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
